version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: database
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_PASSWORD
      - MONGO_INITDB_DATABASE=$DATABASE_NAME
    ports:
      - $DATABASE_LOCAL_PORT:$DATABASE_DOCKER_PORT
    volumes:
      - db:/data/db

  api:
    container_name: api
    build:
      context: .
      target: development
    env_file: ./.env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$DATABASE_USER
      - DB_PASSWORD=$DATABASE_PASSWORD
      - DB_NAME=$DATABASE_NAME
      - DB_PORT=$DATABASE_DOCKER_PORT
    stdin_open: true
    tty: true
    # command: npm run start:prod
    command: npm run start:dev
volumes:
  db:
